//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTracks.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applicant_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Applicant_Master()
        {
            this.Job_Applicant_Master = new HashSet<Job_Applicant_Master>();
        }
    
        public int AppLicant_id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Last_Qualification { get; set; }
        public Nullable<int> PassOutYear { get; set; }
        public Nullable<int> YearOfExperience { get; set; }
        public string Resume { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Applicant_Master> Job_Applicant_Master { get; set; }
    }
}
