//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTracks.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Master
    {
        public int Job_id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Tech_Stack { get; set; }
        public string status { get; set; }
        public Nullable<int> Company_Id { get; set; }
        public Nullable<int> TeamLeader_Id { get; set; }
        public Nullable<int> Recruiter_Id { get; set; }
    
        public virtual Company_Master Company_Master { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
