//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTracks.Areas.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Applicant_Master
    {
        public int Job_Id { get; set; }
        public Nullable<int> Recuriter_ID { get; set; }
        public Nullable<int> Applicant_ID { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
    
        public virtual Applicant_Master Applicant_Master { get; set; }
        public virtual User User { get; set; }
    }
}
