//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobTracks.Areas.Admin.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JobTracksEntities : DbContext
    {
        public JobTracksEntities()
            : base("name=JobTracksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applicant_Master> Applicant_Master { get; set; }
        public virtual DbSet<Company_Master> Company_Master { get; set; }
        public virtual DbSet<Job_Applicant_Master> Job_Applicant_Master { get; set; }
        public virtual DbSet<Job_Master> Job_Master { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
